### ISSUE TITLE
Missing synchronization and multiline exception messages

### ISSUE THREAD

**Issue by ritzow** [hkupty/penna#28] opened 2023-03-12 23:15 UTC
I believe the lack of synchronization of penna.core.sink.SinkImpl#write calls across threads can cause message corruption.

For example, you can try this program:

```java
import java.util.concurrent.Executors;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class StdoutTest {
    
    private static final Logger TEST_LOGGER = LoggerFactory.getLogger("testlogger");
    
    @Test
    void run() {
        try(var scope = Executors.newFixedThreadPool(10)) {
            for(int i = 0; i < 10; i++) {
                scope.submit(() -> {
                    try {
                        var ex = new IllegalArgumentException("wrong type!!!\nok???", new RuntimeException("hello", new ArrayIndexOutOfBoundsException(5)));
                        ex.addSuppressed(new RuntimeException());
                        throw ex;
                    } catch(Exception e) {
                        TEST_LOGGER.atInfo()
                            .addKeyValue("version", 5)
                            .addKeyValue("hello", "a\ncouple\nlines")
                            .setCause(e)
                            .addKeyValue("blah", ("[" + Thread.currentThread().threadId() + "]").repeat(1000))
                            .log("Hello \n{}!", "world");
                    }
                });
            }
        }
    }
}

```

Multiple messages will be occasionally intertwined at key "blah". And exceptions will occassionally be missing the text after "wrong type!!!" (either because there's something funky with how Jackson is being used, or Jackson is flushing/writing before adding "\n").

**Comment by hkupty** [comment] 2023-03-12 23:44
Hi! Thanks for the issue!

Unfortunately, I couldn't reproduce it. In my tests, using your snippet, I got [this output](https://pastebin.com/TEB4C3Ri), which seems to be ordered correctly. I even increased the number of threads to 32.

I noticed you are using jdk 19 features (i.e. [`threadId`](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/Thread.html#threadId())) so I am wondering if it might be a JVM issue?

FWIW, everything is set to be `ThreadLocal` within Penna, so it could be that for that particular JVM version something changed w/ the FileWriter and/or FileDescriptor code?

Also, might be helpful for me to know which version of jackson you are using, so I can isolate that as a possible cause.

**Comment by hkupty** [comment] 2023-03-12 23:47
Ok, definitely something to do with JDK version. When using with JDK 17 I didn't get anything, but at JDK 19 it does pop up immediately.

**Comment by hkupty** [comment] 2023-03-12 23:50
I'd imagine its related to buffering... I'll try to increase the number of threads in 17, but from my tests, we're getting 1500+ log messages/ms, all without a single issue, even with ~32 threads.

**Comment by hkupty** [comment] 2023-03-12 23:57
Now, it doesn't make any sense because the `Sink` is `ThreadLocal` to the logger, which means that each thread, while sharing the same logger, will get an individual sink, with an individual message object. It is definitely something to do with how the FileWriter deals with stdout.

**Comment by hkupty** [comment] 2023-03-13 00:01
I can also say that the problem remains, though with fewer occurrences, if I switch to using `new OutputStreamWriter(System.out)` instead.

**Comment by hkupty** [comment] 2023-03-13 00:02
Hum, so maybe that was it. I can imagine it was locking on stdout before and now it does not. Makes sense. It should be an easy fix.

**Comment by hkupty** [comment] 2023-03-13 00:23
That impairs performance considerably. I have actually found another solution, though still not 100% tested. Can you please try #29 ? from my local tests, it seems to produce perfect json messages without any issues.

**Comment by hkupty** [comment] 2023-03-13 00:32
I'll keep testing tomorrow

**Comment by hkupty** [comment] 2023-03-13 06:58
I initialised the buffer with 32kb because I didn't want to think much on it to test the implementation. I might lower it to 2kb or 4kb, which should be a very large json message already. For larger messages we should resort to trimming the stacktrace, limiting the recursion and the depth of the stack trace. 

This grows per thread, not per logger. Given you have diminished returns by increasing your thread number above a certain amount, I don't think real apps will have more than 100 threads, which is already a very large number, so we're saying 200~400kb, which is still reasonable.

I'll of course test those numbers, so it could be that we end up having 8kb, 16kb or even larger than 32kb, though I find it unrealistic that we'd need more that that. 32kb in a 100 threads app is ~3Mb, which might still be reasonable. It is unrealistic to imagine an app with such high thread count will have a narrow heap. It can make sense to have a configurable buffer size if an app requires even larger messages or wants to fine-tune it. Honestly, I think log message with over a thousand characters is already too big, but penna needs to be safe against such unusual use cases.

The reason why I think it works is because we transfer the whole buffer to the stdout at once, atomically.

**Comment by hkupty** [comment] 2023-03-15 06:54
Ok, I don't know what happened, but version `0.5.1` should be published now. I'll close this issue, but feel free to reopen if the problem persists.

**Closed by hkupty** 2023-03-15 06:54 UTC
